services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
  redis:
    image: redis:alpine
  django:
    build:
      context: ./server
      dockerfile: Dockerfile
    entrypoint: ["./docker-entrypoint.sh"]
    volumes:
      - ./server:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    environment:
      DJANGO_ENVIRONMENT: "local"
  react:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/:/code
    ports:
      - 5173:5173
    depends_on:
      - django
    tty: true
  manage:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: /bin/sh -c "python manage.py $COMMAND"
    volumes:
      - ./server:/code
    environment:
      DJANGO_ENVIRONMENT: "local"

volumes:
  pgdata:
