# Generated by Django 4.2 on 2024-09-09 03:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hash', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg12345678', length=8, max_length=8, prefix='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('acreage', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
