# Generated by Django 4.2 on 2024-09-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ('name',)},
        ),
    ]
