# Generated by Django 4.2 on 2024-09-09 14:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_alter_field_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='location',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
