# Generated by Django 4.2 on 2024-09-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_alter_field_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ('-last_updated',)},
        ),
    ]
