# Generated by Django 4.2 on 2024-09-09 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fields', '0004_alter_field_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='auth.group'),
        ),
    ]
